# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Reshab Kansakar'
description: 'Website Under Construction.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#dribbble: ''
#facebook: ''
#twitter: ''
#linkedin: ''
#instagram: ''
#pinterest: ''
#youtube: ''
#github-user: ''
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#rubygems: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
#email: ''
#messenger: ''

#social-links-order: [github-user, facebook, twitter, instagram, tumblr, pinterest, linkedin, youtube, vk, weibo, dribbble, messenger, blog_url, email]

# Advanced settings
#plugins:
#  - jekyll-remote-theme
