# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Reshab Kansakar'
description: 'Website Under Construction.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'
